### ISSUE TITLE
error could not create necessary folder

### ISSUE THREAD

**Issue by nenouchkaa** [ljvillanueva/pumilio#51]
i have this message when i try to add files:

Error: error could not create necessary folder
/var/www/tip2015//sounds/sounds/1/72

is this double "//" the problem?

i am using Pumilio v. 3.0.0.dev

Thanks :)

**Comment by ljvillanueva** [comment]
The development version of v 3 was very broken. Could be related to this issue. Try again when I release the new version soon.
